### ISSUE TITLE
Wahcade crashes on launch after install Ubuntu 16.04

### ISSUE THREAD

**Issue by sairuk** [sairuk/wahcade#2]
Everytime I try to launch wahcade, it crashes. This started after install Ubuntu 16.04.

version: wahcade_20131107mahcade_all

OS: Ubuntu 16.04 (64bits)

Pyhton error:

Traceback (most recent call last):
  File "wahcade.py", line 86, in <module>
    app = WinMain(options)
  File "/usr/local/share/games/wahcade/win_main.py", line 313, in **init**
    self.scrsaver = WinScrSaver(self)
  File "/usr/local/share/games/wahcade/win_scrsaver.py", line 105, in **init**
    self.video_player.set_volume(0)
AttributeError: WinScrSaver instance has no attribute 'video_player'

wahcade log is empty.

**Comment by sairuk** [comment]
First reported on launchpad by https://launchpad.net/~kanito8a-gmail

**Comment by sairuk** [comment]
this needs to be tested on later versions
