### ISSUE TITLE
 glib.gerror couldn't recognize the image file format for file Edit

### ISSUE THREAD

**Issue by sairuk** [sairuk/wahcade#3]
Originally reported as #1665132 on launchpad

When I try to run mahcade, I get the following error:

Traceback (most recent call last):
  File "wahcade.py", line 86, in <module>
    app = WinMain(options)
  File "/usr/local/share/games/wahcade/win_main.py", line 436, in __init__
    self.on_sclGames_changed()
  File "/usr/local/share/games/wahcade/win_main.py", line 949, in on_sclGames_changed
    self.display_scaled_image(img, img_filename, self.keep_aspect, img.get_data('text-rotation'))
  File "/usr/local/share/games/wahcade/wc_common.py", line 278, in display_scaled_image
    pb = self.get_scaled_pixbuf(img, img_filename, keep_aspect, rotate=rotate)
  File "/usr/local/share/games/wahcade/wc_common.py", line 236, in get_scaled_pixbuf
    pb = gtk.gdk.PixbufAnimation(img_filename)
glib.GError: No se pudo reconocer el formato de imagen del archivo «/home/usuario/Juegos/Mame/snap/sf2.avi»

How do I fix it?

Thank you.

**Comment by sairuk** [comment]
Fixed in https://github.com/sairuk/wahcade/commit/04abeaa5f370fd00fc5b01783de7486c02d11767
